export default {
  //images
  logo: require('../../assets/logo/logo.png'),
  splash: require('../../assets/images/splash.png'),
  bitex: require('../../assets/images/bitex.png'),
  loading: require('../../assets/images/loading.png'),
  wel1: require('../../assets/images/wel1.png'),
  wel2: require('../../assets/images/wel2.png'),
  wel3: require('../../assets/images/wel3.png'),
  email_login: require('../../assets/images/email_login.png'),
  phone_login: require('../../assets/images/phone_login.png'),
  otp: require('../../assets/images/otpverify.png'),
  create_pass: require('../../assets/images/create_pass.png'),
  forgot_pass: require('../../assets/images/forgot_pass.png'),
  select_location: require('../../assets/images/select_location.png'),
  path: require('../../assets/images/path.png'),
  bg_orange: require('../../assets/images/bg_orange.png'),
  portfolio_bg: require('../../assets/images/portfolio_bg.png'),

  //icons

  back: require('../../assets/icons/back.png'),
  email: require('../../assets/icons/email.png'),
  pass: require('../../assets/icons/pass.png'),
  down: require('../../assets/icons/down.png'),
  checked: require('../../assets/icons/checked.png'),
  eye: require('../../assets/icons/eye.png'),
  picker: require('../../assets/icons/picker.png'),
  home: require('../../assets/icons/home.png'),
  wallet: require('../../assets/icons/wallet.png'),
  settings: require('../../assets/icons/settings.png'),
  chats: require('../../assets/icons/chats.png'),
  plus: require('../../assets/icons/plus.png'),
  drawer: require('../../assets/icons/drawer.png'),
  bell: require('../../assets/icons/bell.png'),
  arrow_down_white: require('../../assets/icons/arrow_down_white.png'),
  arrow_up_white: require('../../assets/icons/arrow_up_white.png'),
  ethereum: require('../../assets/icons/ethereum.png'),
  bitcoin: require('../../assets/icons/bitcoin.png'),
  ethernium_p: require('../../assets/icons/ethernium_p.png'),
  send: require('../../assets/icons/send.png'),
  receive: require('../../assets/icons/receive.png'),
  buy: require('../../assets/icons/buy.png'),
  swap: require('../../assets/icons/swap.png'),
  achain: require('../../assets/icons/achain.png'),
  tron: require('../../assets/icons/tron.png'),
  etherium: require('../../assets/icons/etherium.png'),
  binance_coin: require('../../assets/icons/binance_coin.png'),
  pound: require('../../assets/icons/pound.png'),
  tether: require('../../assets/icons/tether.png'),
  bitcoin_cash: require('../../assets/icons/bitcoin_cash.png'),
  search: require('../../assets/icons/search.png'),
  dots: require('../../assets/icons/dots.png'),
  favorite: require('../../assets/icons/favorite.png'),
  candle_icon: require('../../assets/icons/candle_icon.png'),
  maximise_graph: require('../../assets/icons/maximise_graph.png'),
  image: require('../../assets/icons/image.png'),
  next: require('../../assets/icons/next.png'),
  lock_white: require('../../assets/icons/lock_white.png'),
  wallet_white: require('../../assets/icons/wallet_white.png'),
  bell_white: require('../../assets/icons/bell_white.png'),
  setting_white: require('../../assets/icons/setting_white.png'),
  logout: require('../../assets/icons/logout.png'),

  news_letter: require('../../assets/icons/news_letter.png'),
  txt_message: require('../../assets/icons/txt_message.png'),
  phonecall: require('../../assets/icons/phonecall.png'),
  currency: require('../../assets/icons/currency.png'),
  language: require('../../assets/icons/language.png'),
  link: require('../../assets/icons/link.png'),
  scanning: require('../../assets/icons/scanning.png'),
  tick: require('../../assets/icons/tick.png'),
};
